/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cseproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Tohid_Fahim
 */
public class adminlogin extends javax.swing.JFrame {

    /**
     * Creates new form adminlogin
     */
    public adminlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        adminlogin = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        unfield = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        passfield = new javax.swing.JPasswordField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(901, 522));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(470, 400, 110, 30);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(620, 400, 120, 30);

        adminlogin.setFont(new java.awt.Font("Blinded by desire", 0, 48)); // NOI18N
        adminlogin.setForeground(new java.awt.Color(255, 255, 255));
        adminlogin.setText("admin member LOGIN");
        getContentPane().add(adminlogin);
        adminlogin.setBounds(140, 50, 520, 80);

        username.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username  ");
        getContentPane().add(username);
        username.setBounds(140, 200, 190, 50);

        unfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfieldActionPerformed(evt);
            }
        });
        getContentPane().add(unfield);
        unfield.setBounds(320, 210, 260, 40);

        password.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        getContentPane().add(password);
        password.setBounds(140, 290, 170, 60);
        getContentPane().add(passfield);
        passfield.setBounds(320, 300, 260, 40);

        background.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tohid_Fahim\\Desktop\\viRjdLn.png")); // NOI18N
        background.setText("jLabel1");
        background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        background.setMaximumSize(new java.awt.Dimension(1761, 1022));
        background.setMinimumSize(new java.awt.Dimension(1761, 1022));
        background.setPreferredSize(new java.awt.Dimension(1761, 1022));
        background.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(background);
        background.setBounds(0, -20, 930, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unfieldActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        welcome ob = new welcome();
        ob.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String sn = "admin";
        String sp = "admin";
        if(sn.equals(unfield.getText())&&sp.equals(passfield.getText()))
        {
            new adminpage().setVisible(true);
            setVisible(false);
        }
        
        else 
        {
            JOptionPane.showMessageDialog(null, "Incorrect Username & Password!");
            unfield.setText(null);
            passfield.setText(null);
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminlogin;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JLabel password;
    private javax.swing.JButton submit;
    private javax.swing.JTextField unfield;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
