/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cseproject;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
public class adminwork extends javax.swing.JFrame {

    /**
     * Creates new form adminwork
     */
  Double ct[]= new Double[10];
  
  String ct_1,ct_2,ct_3,ct_4,f_m,a_m,tday,abs, quiz, viba, finalxm, atde ;
  Double c1,c2,c3,c4,f,a,sum,vg,temp,total,total1,avg_ct,t,amark,amark1,cgpa=0.0,squiz,sviba,sfinalxm,satde,sumall;
  int i,j;
  
  Double cg[] = new Double[9];
  int k=0;
  DecimalFormat df=new DecimalFormat(".##");
     
    public adminwork() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fetm = new javax.swing.JTextField();
        ct4 = new javax.swing.JTextField();
        ct3 = new javax.swing.JTextField();
        ct1 = new javax.swing.JTextField();
        ct2 = new javax.swing.JTextField();
        gpatm = new javax.swing.JTextField();
        fes = new javax.swing.JTextField();
        ls = new javax.swing.JTextField();
        bvs = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        gpas = new javax.swing.JTextField();
        sesubject = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        roll = new javax.swing.JTextField();
        subject = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        fcgpa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tdays = new javax.swing.JTextField();
        amraks = new javax.swing.JTextField();
        atd = new javax.swing.JTextField();
        am = new javax.swing.JTextField();
        absent = new javax.swing.JTextField();
        aa = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 520));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CT 01");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 200, 40, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CT 02");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 240, 40, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CT 03");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 280, 40, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CT 04");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(80, 320, 40, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Final Exam");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(240, 220, 90, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Attendence");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(240, 270, 90, 15);

        fetm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetmActionPerformed(evt);
            }
        });
        getContentPane().add(fetm);
        fetm.setBounds(370, 210, 70, 30);
        getContentPane().add(ct4);
        ct4.setBounds(120, 320, 70, 30);

        ct3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct3ActionPerformed(evt);
            }
        });
        getContentPane().add(ct3);
        ct3.setBounds(120, 280, 70, 30);

        ct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct1ActionPerformed(evt);
            }
        });
        getContentPane().add(ct1);
        ct1.setBounds(120, 200, 70, 30);
        getContentPane().add(ct2);
        ct2.setBounds(120, 240, 70, 30);

        gpatm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpatmActionPerformed(evt);
            }
        });
        getContentPane().add(gpatm);
        gpatm.setBounds(370, 380, 70, 30);

        fes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fesActionPerformed(evt);
            }
        });
        getContentPane().add(fes);
        fes.setBounds(720, 250, 80, 20);
        getContentPane().add(ls);
        ls.setBounds(720, 190, 80, 20);
        getContentPane().add(bvs);
        bvs.setBounds(720, 220, 80, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Board Viba");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(600, 220, 70, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Final Exam");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(600, 250, 70, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Attendence");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(600, 300, 80, 15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Quiz");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(600, 190, 40, 15);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Total GPA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 380, 100, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Total GPA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 380, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Total CGPA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 440, 130, 40);

        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(670, 450, 120, 30);

        gpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpasActionPerformed(evt);
            }
        });
        getContentPane().add(gpas);
        gpas.setBounds(730, 380, 70, 30);

        sesubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discrete Mathematics", "Numerical Method", "Electronics", "CSE Project" }));
        sesubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesubjectActionPerformed(evt);
            }
        });
        getContentPane().add(sesubject);
        sesubject.setBounds(600, 130, 200, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student's Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 60, 210, 40);

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 1, 9));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(240, 60, 200, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Roll No");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 60, 120, 40);

        roll.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        roll.setForeground(new java.awt.Color(252, 0, 0));
        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        getContentPane().add(roll);
        roll.setBounds(600, 60, 200, 40);

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discrete Mathematics", "Numerical Method", "Mathematics", "Electronics", "Accounting & Management" }));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });
        getContentPane().add(subject);
        subject.setBounds(240, 130, 200, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sessional");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 130, 210, 40);

        fcgpa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fcgpa.setForeground(new java.awt.Color(255, 0, 8));
        fcgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcgpaActionPerformed(evt);
            }
        });
        getContentPane().add(fcgpa);
        fcgpa.setBounds(330, 440, 160, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Theory Marks");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 130, 210, 40);

        tdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdaysActionPerformed(evt);
            }
        });
        getContentPane().add(tdays);
        tdays.setBounds(380, 260, 60, 20);

        amraks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amraksActionPerformed(evt);
            }
        });
        getContentPane().add(amraks);
        amraks.setBounds(380, 320, 60, 20);

        atd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atdActionPerformed(evt);
            }
        });
        getContentPane().add(atd);
        atd.setBounds(740, 280, 60, 20);

        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });
        getContentPane().add(am);
        am.setBounds(740, 340, 60, 20);

        absent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absentActionPerformed(evt);
            }
        });
        getContentPane().add(absent);
        absent.setBounds(380, 290, 60, 20);

        aa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aaActionPerformed(evt);
            }
        });
        getContentPane().add(aa);
        aa.setBounds(740, 310, 60, 20);

        jButton5.setText("Attendence Marks");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(600, 340, 120, 23);

        jButton4.setText("Attendence Marks");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 320, 120, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tohid_Fahim\\Desktop\\Abstract-HD-Wallpapers.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 860, 510);

        jTextField11.setText("Attendence");
        getContentPane().add(jTextField11);
        jTextField11.setBounds(460, 270, 70, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Theory Marks");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 150, 210, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
        String s;
        s=subject.getSelectedItem().toString();
        if (s.equals("Discrete Mathematics"))
        {
            ct1.setText(null);
            ct2.setText(null);
            ct3.setText(null);
            ct4.setText(null);
            fetm.setText(null);
            tdays.setText(null);
            absent.setText(null);        
            amraks.setText(null);
            gpatm.setText(null);
        }
        if (s.equals("Numerical Method"))
        {
            ct1.setText(null);
            ct2.setText(null);
            ct3.setText(null);
            ct4.setText(null);
            fetm.setText(null);
            tdays.setText(null);
            absent.setText(null);        
            amraks.setText(null);
            gpatm.setText(null);
        }
       if (s.equals("Mathematics"))
        {
            ct1.setText(null);
            ct2.setText(null);
            ct3.setText(null);
            ct4.setText(null);
            fetm.setText(null);
            tdays.setText(null);
            absent.setText(null);        
            amraks.setText(null);
            gpatm.setText(null);
        }
       
       if (s.equals("Electronics"))
        {
            ct1.setText(null);
            ct2.setText(null);
            ct3.setText(null);
            ct4.setText(null);
            fetm.setText(null);
            tdays.setText(null);
            absent.setText(null);        
            amraks.setText(null);
            gpatm.setText(null);
        }
        if (s.equals("Accounting & Management"))
        {
            ct1.setText(null);
            ct2.setText(null);
            ct3.setText(null);
            ct4.setText(null);
            fetm.setText(null);
            tdays.setText(null);
            absent.setText(null);        
            amraks.setText(null);
            gpatm.setText(null);
        }
        
    }//GEN-LAST:event_subjectActionPerformed

    private void ct3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct3ActionPerformed

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollActionPerformed

    private void sesubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesubjectActionPerformed
        // TODO add your handling code here:
        String ss;
        ss=sesubject.getSelectedItem().toString();
        
        if (ss.equals("Discrete Mathematics"))
        {
            ls.setText(null);
            bvs.setText(null);
            fes.setText(null);
            atd.setText(null);
            aa.setText(null);
            am.setText(null);
            gpas.setText(null);        
        }
        if (ss.equals("Numerical Method"))
        {
            ls.setText(null);
            bvs.setText(null);
            fes.setText(null);
            atd.setText(null);
            aa.setText(null);
            am.setText(null);
            gpas.setText(null);        
        }
        if (ss.equals("Electronics"))
        {
            ls.setText(null);
            bvs.setText(null);
            fes.setText(null);
            atd.setText(null);
            aa.setText(null);
            am.setText(null);
            gpas.setText(null);        
        }
        if (ss.equals("CSE Project"))
        {
            ls.setText(null);
            bvs.setText(null);
            fes.setText(null);
            atd.setText(null);
            aa.setText(null);
            am.setText(null);
            gpas.setText(null);        
        }
    }//GEN-LAST:event_sesubjectActionPerformed

    private void fcgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcgpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcgpaActionPerformed

    private void ct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct1ActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        new adminpage().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void gpatmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpatmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpatmActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void amraksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amraksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amraksActionPerformed

    private void tdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdaysActionPerformed

    private void atdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atdActionPerformed

    private void amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amActionPerformed

    private void absentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_absentActionPerformed

    private void fesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fesActionPerformed

    private void aaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        quiz = ls.getText();
        squiz = Double.parseDouble(quiz);
        
        viba = bvs.getText();
        sviba = Double.parseDouble(viba);
        
        finalxm = fes.getText();
        sfinalxm = Double.parseDouble(finalxm);
        
        atde = am.getText();
        satde = Double.parseDouble(atde);
                 
        total1 = squiz+sviba+sfinalxm+satde;
         if (total1>=80)
         {
             cgpa+=4.0*1.5;
         }
         if (total1>=75&&total1<80)
         {
             cgpa+=3.75*1.5;
         }
         if (total1>=70&&total1<75)
         {
             cgpa+=3.50*1.5;
         }
         if (total1>=65&&total1<70)
         {
             cgpa+=3.25*1.5;
         }
         if (total1>=60&&total1<65)
         {
             cgpa+=3.00*1.5;
         }
         if (total1>=55&&total1<60)
         {
             cgpa+=2.75*1.5;
         }
         if (total1>=50&&total1<55)
         {
             cgpa+=2.50*1.5;
         }
         if (total1>=45&&total1<50)
         {
             cgpa+=2.25*1.5;
         }
         if (total1>=40&&total1<45)
         {
             cgpa+=2*1.5;
         }
         gpas.setText(""+df.format(cgpa/1.5));
         cg[k] = cgpa;
         k++;
         cgpa = 0.0;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fetmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fetmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ct_1=ct1.getText();
        ct[0]=Double.parseDouble(ct_1);
         ct_2=ct2.getText();
        ct[1]=Double.parseDouble(ct_2);
        ct_3=ct3.getText();
        ct[2]=Double.parseDouble(ct_3);
        ct_4=ct4.getText();
        ct[3]=Double.parseDouble(ct_4);
        
        for(i=0;i<4;i++)
        {
            for(j=i+1;j<4;j++)
            {
                if (ct[i]<ct[j])
                {
                    temp=ct[i];
                    ct[i]=ct[j];
                    ct[j]=temp;
                }
            }
        }
        avg_ct=(ct[0]+ct[1]+ct[2])/3.0;
        f_m=fetm.getText();
        f=Double.parseDouble(f_m);
        total=avg_ct+f+amark;
         if (total>=80)
         {
             cgpa+=4.0*3.0;
         }
         if (total>=75&&total<80)
         {
             cgpa+=3.75*3.0;
         }
         if (total>=70&&total<75)
         {
             cgpa+=3.50*3.0;
         }
         if (total>=65&&total<70)
         {
             cgpa+=3.25*3.0;
         }
         if (total>=60&&total<65)
         {
             cgpa+=3.00*3.0;
         }
         if (total>=55&&total<60)
         {
             cgpa+=2.75*3.0;
         }
         if (total>=50&&total<55)
         {
             cgpa+=2.50*3.0;
         }
         if (total>=45&&total<50)
         {
             cgpa+=2.25*3.0;
         }
         if (total>=40&&total<45)
         {
             cgpa+=2*3.0;
         }
         gpatm.setText(""+df.format(cgpa/3.0));
         cg[k]=cgpa;
         k++;
         cgpa = 0.0;
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        sumall=0.0;
        for(k=0; k<9; k++)
        {
            sumall = sumall + cg[k];
        }
        fcgpa.setText(""+df.format(sumall/21.0));
        try
        { 
            String url="jdbc:derby://localhost:1527/reg";
            String user = "tohidfahim";
            String password = "tohidfahim";
            
            Connection con = DriverManager.getConnection(url, user, password);
            Statement st = con.createStatement();
           
            String nrp = "INSERT INTO CGPA(NAME, ROLL, CGPA) VALUES ('"+name.getText()+"', '"+roll.getText()+"', '"+fcgpa.getText()+"')";
            st.executeUpdate(nrp);
             
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Double cal;
        tday=tdays.getText();
        t=Double.parseDouble(tday);
        abs=absent.getText();
        a=Double.parseDouble(abs);
        
        cal=(double)(((t-a)*100)/t);
         
        if (cal>90)
        {
            amark=8.0;
        }
       else  if (cal>80&&cal<=90)
        {
            amark=7.0;
        }
       else   if (cal>70&&cal<=80)
        {
            amark=6.0;
        }
       else    if (cal>60&&cal<=70)
        {
            amark=5.0;
        }
           else  amark=0.0;  
           amraks.setText(""+df.format(amark));
          
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Double cal;
        tday=atd.getText();
        t=Double.parseDouble(tday);
        abs=aa.getText();
        a=Double.parseDouble(abs);
        
        cal=(double)(((t-a)*100)/t);
         
        if (cal>90)
        {
            amark1=8.0;
        }
       else  if (cal>80&&cal<=90)
        {
            amark1=7.0;
        }
       else   if (cal>70&&cal<=80)
        {
            amark1=6.0;
        }
       else    if (cal>60&&cal<=70)
        {
            amark1=5.0;
        }
           else  amark1=0.0;  
           am.setText(""+df.format(amark1));
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminwork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminwork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aa;
    private javax.swing.JTextField absent;
    private javax.swing.JTextField am;
    private javax.swing.JTextField amraks;
    private javax.swing.JTextField atd;
    private javax.swing.JButton backbutton;
    private javax.swing.JTextField bvs;
    private javax.swing.JTextField ct1;
    private javax.swing.JTextField ct2;
    private javax.swing.JTextField ct3;
    private javax.swing.JTextField ct4;
    private javax.swing.JTextField fcgpa;
    private javax.swing.JTextField fes;
    private javax.swing.JTextField fetm;
    private javax.swing.JTextField gpas;
    private javax.swing.JTextField gpatm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField ls;
    private javax.swing.JTextField name;
    private javax.swing.JTextField roll;
    private javax.swing.JComboBox<String> sesubject;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JTextField tdays;
    // End of variables declaration//GEN-END:variables
}
