/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cseproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static javax.swing.Action.NAME;
import javax.swing.JOptionPane;

/**
 *
 * @author Tohid_Fahim
 */
public class studentlogin extends javax.swing.JFrame {

    /**
     * Creates new form studentlogin
     */
    public studentlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        studentlogin = new javax.swing.JLabel();
        rollno = new javax.swing.JLabel();
        roll = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        username1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setPreferredSize(new java.awt.Dimension(901, 522));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setLayout(null);

        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(470, 400, 110, 30);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(620, 400, 120, 30);

        studentlogin.setFont(new java.awt.Font("Blinded by desire", 0, 48)); // NOI18N
        studentlogin.setForeground(new java.awt.Color(255, 255, 255));
        studentlogin.setText("Student LOGIN");
        jPanel1.add(studentlogin);
        studentlogin.setBounds(140, 60, 410, 80);

        rollno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rollno.setForeground(new java.awt.Color(255, 255, 255));
        rollno.setText("Roll No");
        jPanel1.add(rollno);
        rollno.setBounds(140, 220, 190, 50);

        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        jPanel1.add(roll);
        roll.setBounds(320, 230, 260, 40);
        jPanel1.add(pass);
        pass.setBounds(320, 310, 260, 40);

        password.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        jPanel1.add(password);
        password.setBounds(140, 300, 170, 60);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(320, 150, 260, 40);

        username1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        username1.setForeground(new java.awt.Color(255, 255, 255));
        username1.setText("Username  ");
        jPanel1.add(username1);
        username1.setBounds(140, 140, 190, 50);

        background.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tohid_Fahim\\Desktop\\viRjdLn.png")); // NOI18N
        background.setText("jLabel1");
        background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        background.setMaximumSize(new java.awt.Dimension(1761, 1022));
        background.setMinimumSize(new java.awt.Dimension(1761, 1022));
        background.setPreferredSize(new java.awt.Dimension(1761, 1022));
        background.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(background);
        background.setBounds(0, 0, 930, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        
        try
        {
            String url="jdbc:derby://localhost:1527/reg";
            String user = "tohidfahim";
            String password = "tohidfahim";
            
            Connection con = DriverManager.getConnection(url, user, password);
            Statement st = con.createStatement();
            
            String nrpa = "SELECT * FROM STUDENT WHERE ROLL = '"+roll.getText()+"'";
            ResultSet rs = st.executeQuery(nrpa);
            
            while(rs.next())
            {
               if (rs.getString(1).equals(name.getText()) && rs.getString(2).equals(roll.getText()) && rs.getString(3).equals(pass.getText()))
               {
                   new studentpage().setVisible(true);
                   setVisible(false);
               } 
               else if(!rs.getString(3).equals(pass.getText()))
               {
                   JOptionPane.showMessageDialog(null, "Wrong Username & Password!");
                   name.setText(null);
                   pass.setText(null);
                   roll.setText(null);
               }
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        welcome ob = new welcome();
        ob.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel password;
    public static javax.swing.JTextField roll;
    private javax.swing.JLabel rollno;
    private javax.swing.JLabel studentlogin;
    private javax.swing.JButton submit;
    private javax.swing.JLabel username1;
    // End of variables declaration//GEN-END:variables
}
