/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cseproject;

import static cseproject.studentlogin.roll;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Tohid_Fahim
 */
public class studentpage extends javax.swing.JFrame {

    /**
     * Creates new form studentpage
     */
    public studentpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        submitbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        cnpsdsa = new javax.swing.JLabel();
        cnp = new javax.swing.JPasswordField();
        prevpass = new javax.swing.JLabel();
        pp = new javax.swing.JPasswordField();
        newpass = new javax.swing.JLabel();
        np = new javax.swing.JPasswordField();
        resultcheck = new javax.swing.JCheckBox();
        otherscheck = new javax.swing.JCheckBox();
        resetpasslevel = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        option = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(840, 522));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel2.setLayout(null);

        submitbutton.setText("SUBMIT");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(submitbutton);
        submitbutton.setBounds(420, 430, 110, 30);

        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(backbutton);
        backbutton.setBounds(570, 430, 120, 30);

        cnpsdsa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cnpsdsa.setForeground(new java.awt.Color(255, 255, 255));
        cnpsdsa.setText("Confirm New Password");
        jPanel2.add(cnpsdsa);
        cnpsdsa.setBounds(60, 390, 160, 20);
        jPanel2.add(cnp);
        cnp.setBounds(240, 390, 190, 20);

        prevpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prevpass.setForeground(new java.awt.Color(255, 255, 255));
        prevpass.setText("Previous Password");
        jPanel2.add(prevpass);
        prevpass.setBounds(60, 310, 160, 20);

        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });
        jPanel2.add(pp);
        pp.setBounds(240, 310, 190, 20);

        newpass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newpass.setForeground(new java.awt.Color(255, 255, 255));
        newpass.setText("New Password");
        jPanel2.add(newpass);
        newpass.setBounds(60, 350, 160, 20);

        np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npActionPerformed(evt);
            }
        });
        jPanel2.add(np);
        np.setBounds(240, 350, 190, 20);

        resultcheck.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        resultcheck.setForeground(new java.awt.Color(255, 0, 0));
        resultcheck.setText("Result");
        resultcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultcheckActionPerformed(evt);
            }
        });
        jPanel2.add(resultcheck);
        resultcheck.setBounds(280, 140, 170, 35);

        otherscheck.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        otherscheck.setForeground(new java.awt.Color(255, 0, 0));
        otherscheck.setText("Others");
        otherscheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherscheckActionPerformed(evt);
            }
        });
        jPanel2.add(otherscheck);
        otherscheck.setBounds(280, 200, 170, 33);

        resetpasslevel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        resetpasslevel.setForeground(new java.awt.Color(255, 255, 255));
        resetpasslevel.setText("Reset Password");
        jPanel2.add(resetpasslevel);
        resetpasslevel.setBounds(60, 240, 200, 60);

        type.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setText("Select Type");
        jPanel2.add(type);
        type.setBounds(60, 120, 170, 60);

        option.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        option.setForeground(new java.awt.Color(255, 255, 255));
        option.setText("Choose Your Option");
        jPanel2.add(option);
        option.setBounds(60, 50, 550, 30);

        background.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tohid_Fahim\\Desktop\\7074.jpg")); // NOI18N
        background.setText("jLabel2");
        background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(background);
        background.setBounds(0, 0, 840, 500);

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(310, 270, 34, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void otherscheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherscheckActionPerformed
        // TODO add your handling code here:
        new studentothers().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_otherscheckActionPerformed

    private void resultcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultcheckActionPerformed
        // TODO add your handling code here:
        new studentresult().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_resultcheckActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        studentlogin ob = new studentlogin();
        ob.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        String s1,s2;
        int i=0;
        try
        { 
            String url="jdbc:derby://localhost:1527/reg";
            String user = "tohidfahim";
            String password = "tohidfahim";
            
            Connection con = DriverManager.getConnection(url, user, password);
            Statement st = con.createStatement();
            
            String s = "SELECT * FROM STUDENT WHERE ROLL = '"+studentlogin.roll.getText()+"' ";
            ResultSet rs = st.executeQuery(s);
            
            while(rs.next())
            {
               if (rs.getString(2).equals(studentlogin.roll.getText()))
               {
                   s1=np.getText();
                   s2=cnp.getText();
                   
                   if (s1.equals(s2)){
                   String ss="UPDATE STUDENT SET PASSWORD='"+ s2 +"'WHERE ROLL='"+studentlogin.roll.getText()+"'";
                   st.execute(ss);
                   JOptionPane.showMessageDialog(null, "Succseefully updated!");
                  
                   new studentlogin().setVisible(true);
                   setVisible(false);
                   break;
                   }
                   else 
                   {JOptionPane.showMessageDialog(null, "Passwords Mismatch!");
                   np.setText(null);
                   cnp.setText(null);
                   }
                   
               }
                  
               } 
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }     
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppActionPerformed

    private void npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel background;
    private javax.swing.JPasswordField cnp;
    private javax.swing.JLabel cnpsdsa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel newpass;
    private javax.swing.JPasswordField np;
    private javax.swing.JLabel option;
    private javax.swing.JCheckBox otherscheck;
    private javax.swing.JPasswordField pp;
    private javax.swing.JLabel prevpass;
    private javax.swing.JLabel resetpasslevel;
    private javax.swing.JCheckBox resultcheck;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
