/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cseproject;

/**
 *
 * @author Tohid_Fahim
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        admincheck = new javax.swing.JCheckBox();
        studentcheck = new javax.swing.JCheckBox();
        chooseoption = new javax.swing.JLabel();
        mit = new javax.swing.JLabel();
        mitpic = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(null);

        admincheck.setBackground(new java.awt.Color(102, 102, 102));
        admincheck.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        admincheck.setForeground(new java.awt.Color(255, 255, 255));
        admincheck.setText("ADMIN PANEL");
        admincheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admincheckActionPerformed(evt);
            }
        });
        jPanel2.add(admincheck);
        admincheck.setBounds(670, 230, 200, 60);

        studentcheck.setBackground(new java.awt.Color(102, 102, 102));
        studentcheck.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        studentcheck.setForeground(new java.awt.Color(255, 255, 255));
        studentcheck.setText("STUDENT");
        studentcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentcheckActionPerformed(evt);
            }
        });
        jPanel2.add(studentcheck);
        studentcheck.setBounds(670, 310, 200, 60);

        chooseoption.setBackground(new java.awt.Color(0, 0, 0));
        chooseoption.setFont(new java.awt.Font("Trashbox", 0, 15)); // NOI18N
        chooseoption.setForeground(new java.awt.Color(255, 255, 255));
        chooseoption.setText("   CHOOSE YOUR OPTION     ");
        jPanel2.add(chooseoption);
        chooseoption.setBounds(670, 200, 200, 18);

        mit.setFont(new java.awt.Font("Blinded by desire", 0, 70)); // NOI18N
        mit.setForeground(new java.awt.Color(252, 249, 249));
        mit.setText(" University");
        jPanel2.add(mit);
        mit.setBounds(250, 10, 420, 110);

        mitpic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tohid_Fahim\\Desktop\\MITY1_2055251i.jpg")); // NOI18N
        mitpic.setText("jLabel3");
        jPanel2.add(mitpic);
        mitpic.setBounds(40, 130, 570, 340);

        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tohid_Fahim\\Desktop\\Colorful-HD-Abstract-Wallpaper.jpg")); // NOI18N
        background.setText("MIT SCHOOL AND COLLEGE");
        background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(background);
        background.setBounds(-10, 2, 930, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentcheckActionPerformed
        // TODO add your handling code here:
        if (studentcheck.isSelected())
        {
            register ob=new register();
            ob.setVisible(true);
            setVisible(false);
        }
        
    }//GEN-LAST:event_studentcheckActionPerformed

    private void admincheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admincheckActionPerformed
        // TODO add your handling code here:
        if (admincheck.isSelected())
        {
            adminlogin ob=new adminlogin();
            ob.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_admincheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox admincheck;
    private javax.swing.JLabel background;
    private javax.swing.JLabel chooseoption;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mit;
    private javax.swing.JLabel mitpic;
    private javax.swing.JCheckBox studentcheck;
    // End of variables declaration//GEN-END:variables
}
